// 框架demo/vue-demo-1/src/views/login.vue
<template>
  <div class="login">
    <div class="form_login">
      <el-form
        :model="ruleForm"
        status-icon
        :rules="rules"
        ref="ruleForm"
        label-width="100px"
        class="demo-ruleForm"
      >
        <el-form-item label="账号" prop="username">
          <el-input
            type="password"
            v-model="ruleForm.username"
            autocomplete="off"
          ></el-input>
        </el-form-item>
        <el-form-item label="密码" prop="password">
          <el-input
            type="password"
            v-model="ruleForm.password"
            autocomplete="off"
          ></el-input>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="submitForm('ruleForm')"
            >提交</el-button
          >
          <el-button @click="resetForm('ruleForm')">重置</el-button>
        </el-form-item>
      </el-form>
    </div>
  </div>
</template>

<script>
import { axios } from "@/utils/request";
import Vue from "vue";
export default {
  props: {
    msg: String,
  },
  data() {
    return {
      ruleForm: {
        password: "",
        username: "",
      },
      rules: {
        password: [{ validator: "", trigger: "blur" }],
        username: [{ validator: "", trigger: "blur" }],
      },
    };
  },
  methods: {
    submitForm() {
      console.log(this.$route);
      axios.post("login", this.ruleForm).then((res) => {
        Vue.ls.set("token", res.data.token);
        this.$router.push("/")
      });
    },
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style lang="less">
.login {
  width: 100vw;
  height: 100vh;
  background: url(/assets/bg.jpg);
  margin: auto;
  padding-top: 40vh;
  box-sizing: border-box;
}
.form_login {
  width: 400px;
  margin: auto;
}
</style>

// 框架demo/react-demo/react-demo/src/view/Login.jsx
import { Form, Input, Button, Checkbox } from "antd";
import React, { useState } from "react";
import { useHistory, Route } from "react-router-dom";
import request from "../api/request";
import { Row, Col } from "antd";

import styles from './index.less'

const Login = (props) => {
  const history = useHistory();
  const onFinish = (values) => {
    let { username, password } = values;
    request.post("/login", { username, password }).then((res) => {
      console.log(res);
      const { token } = res.data;
      window.localStorage.setItem("token", token);
      history.push("/dashboard");
    });
  };
  const onFinishFailed = (errorInfo) => {
    console.log("Failed:", errorInfo);
  };
  return (
    <div className={styles.login} style={{backgroundImage:`url(img/bg.jpg)`}}>
      <Row style={{marginTop:'20vh', overflow:"hidden"}}>
        <Col xs={2} sm={4} md={4} lg={4} xl={4}></Col>
        <Col xs={20} sm={16} md={12} lg={12} xl={12}>
          <Form
            name="basic"
            labelCol={{
              span: 8,
            }}
            wrapperCol={{
              span: 16,
            }}
            initialValues={{
              remember: true,
            }}
            onFinish={onFinish}
            onFinishFailed={onFinishFailed}
            autoComplete="off"
          >
            <Form.Item
              label="Username"
              name="username"
              rules={[
                {
                  required: false,
                  message: "Please input your username!",
                },
              ]}
            >
              <Input />
            </Form.Item>

            <Form.Item
              label="Password"
              name="password"
              rules={[
                {
                  required: false,
                  message: "Please input your password!",
                },
              ]}
            >
              <Input.Password />
            </Form.Item>

            <Form.Item
              name="remember"
              valuePropName="checked"
              wrapperCol={{
                offset: 8,
                span: 16,
              }}
            >
              <Checkbox>Remember me</Checkbox>
            </Form.Item>

            <Form.Item
              wrapperCol={{
                offset: 8,
                span: 16,
              }}
            >
              <Button type="primary" htmlType="submit">
                Submit
              </Button>
            </Form.Item>
          </Form>
        </Col>
        <Col xs={2} sm={4} md={4} lg={4} xl={4}></Col>
      </Row>
    </div>
  );
};
export default Login;
