// front/qiankun/packages/react-demo/src/view/User/Login.jsx
import { Form, Input, Button, Checkbox } from "antd";
import React, { useState } from "react";
import { useHistory } from "react-router-dom";
import request from "@/utils/request";
import { Row, Col } from "antd";

import styles from '../index.module.less'

const Login = (props) => {
  const history = useHistory();
  const onFinish = (values) => {
    let { username, password } = values;
    request.post("/login", { username, password }).then((res) => {
      const { token } = res.data;
      window.localStorage.setItem("token", token);
      history.push("/dashboard");
    });
  };
  const onFinishFailed = (errorInfo) => {
    console.log("Failed:", errorInfo);
  };
  return (
    <div className={styles.login} style={{backgroundImage:`url(require(img/bg.jpg))`}}>
      <Row style={{marginTop:'20vh', overflow:"hidden"}}>
        <Col xs={2} sm={4} md={4} lg={4} xl={4}></Col>
        <Col xs={20} sm={16} md={12} lg={12} xl={12}>
          <Form
            name="basic"
            labelCol={{
              span: 8,
            }}
            wrapperCol={{
              span: 16,
            }}
            initialValues={{
              remember: true,
            }}
            onFinish={onFinish}
            onFinishFailed={onFinishFailed}
            autoComplete="off"
          >
            <Form.Item
              label="Username"
              name="username"
              rules={[
                {
                  required: false,
                  message: "Please input your username!",
                },
              ]}
            >
              <Input placeholder="账号：liming"/>
            </Form.Item>

            <Form.Item
              label="Password"
              name="password"
              rules={[
                {
                  required: false,
                  message: "Please input your password!",
                },
              ]}
            >
              <Input.Password placeholder="密码：1"/>
            </Form.Item>

            <Form.Item
              name="remember"
              valuePropName="checked"
              wrapperCol={{
                offset: 8,
                span: 16,
              }}
            >
              <Checkbox>Remember me</Checkbox>
            </Form.Item>

            <Form.Item
              wrapperCol={{
                offset: 8,
                span: 16,
              }}
            >
              <Button type="primary" htmlType="submit">
                Submit
              </Button>
            </Form.Item>
          </Form>
        </Col>
        <Col xs={2} sm={4} md={4} lg={4} xl={4}></Col>
      </Row>
    </div>
  );
};
export default Login;

// 框架demo/vue-demo/vue-demo-pc/src/views/login/index.vue
<template>
  <div class="login">
    <div class="form_login">
      <a-form id="coordinated" :form="form" @submit="handleSubmit">
        <a-form-item label="username">
          <a-input v-decorator="[
              'username',
              {
                rules: [{ required: true, message: 'Please input your note!' }],
              },
            ]" />
        </a-form-item>
        <a-form-item label="password">
          <a-input v-decorator="[
              'password',
              {
                rules: [{ required: true, message: 'Please input your note!' }],
              },
            ]" />
        </a-form-item>
        <a-form-item :wrapper-col="{ span: 12, offset: 5 }">
          <a-button type="primary" html-type="submit"> Submit </a-button>
        </a-form-item>
      </a-form>
    </div>
  </div>
</template>

<script lang='ts'>
import { login } from "@/api";
import { defineComponent, reactive, ref } from "vue";
import { Vue, Component, Watch } from "vue-property-decorator";

interface FormState {
  username: string;
  password: string;
  remember: boolean;
}

@Component
export default class Login extends Vue {
  [x: string]: any;
  formState = reactive<FormState>({
    username: "limng",
    password: "1",
    remember: true,
  });

  data() {
    return {
      form: this.$form.createForm(this, { name: "form_rule" }),
    };
  }

  handleSubmit(e: any) {
    e.preventDefault();
    this.form.getFieldsValue();
    console.log(this.form.getFieldsValue());
    login(this.form.getFieldsValue()).then((res: any) => {
      this.$ls.set("token", res.token);
      this.$router.push("/");
    });
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style lang="less">
.login {
  width: 100vw;
  height: 100vh;
  // background: url(../../assets/bg.jpg) snow -200px;
  box-sizing: border-box;
  display: flex;
  justify-content: center;
  align-items: center;
}
.form_login {
  text-align: center;
  display: flex;
  justify-content: center;
  margin-left: -120px;
}
.el-form-item__label {
  color: #fff;
}
</style>
